import { useMemo, useState } from 'react';
import { useStore } from '../lib/store';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend
} from 'recharts';
import { BarChart2, TrendingUp, GraduationCap, Download, Award, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { format } from 'date-fns';

const COLORS = ['#6366F1', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#06B6D4', '#EC4899', '#84CC16'];

export default function Reports() {
  const { currentUser, students, colleges, departments } = useStore();
  const [selectedCollegeId, setSelectedCollegeId] = useState<string>('ALL');

  if (!currentUser) return null;

  const role = currentUser.role;

  // Scoped students based on role
  const baseStudents = useMemo(() => {
    if (role === 'COLLEGE_ADMIN') return students.filter(s => s.collegeId === currentUser.collegeId);
    if (role === 'DEPARTMENT_ADMIN') return students.filter(s => s.departmentId === currentUser.departmentId);
    return students;
  }, [students, role, currentUser]);

  // Optionally filtered by selected college (SUPER_ADMIN)
  const filteredStudents = useMemo(() => {
    if (role === 'SUPER_ADMIN' && selectedCollegeId !== 'ALL') {
      return baseStudents.filter(s => s.collegeId === selectedCollegeId);
    }
    return baseStudents;
  }, [baseStudents, selectedCollegeId, role]);

  // Summary stats
  const totalStudents = filteredStudents.length;
  const activeCount = filteredStudents.filter(s => s.status === 'ACTIVE').length;
  const graduatedCount = filteredStudents.filter(s => s.status === 'GRADUATED').length;
  const dropoutCount = filteredStudents.filter(s => s.status === 'DROPOUT').length;
  const avgCGPA = totalStudents > 0
    ? (filteredStudents.reduce((sum, s) => sum + s.cgpa, 0) / totalStudents).toFixed(2)
    : '0.00';
  const excellentCount = filteredStudents.filter(s => s.cgpa >= 9).length;

  // CGPA distribution
  const cgpaRanges = [
    { label: '9.0–10', count: filteredStudents.filter(s => s.cgpa >= 9).length, color: '#10B981' },
    { label: '8.0–8.9', count: filteredStudents.filter(s => s.cgpa >= 8 && s.cgpa < 9).length, color: '#6366F1' },
    { label: '7.0–7.9', count: filteredStudents.filter(s => s.cgpa >= 7 && s.cgpa < 8).length, color: '#06B6D4' },
    { label: '6.0–6.9', count: filteredStudents.filter(s => s.cgpa >= 6 && s.cgpa < 7).length, color: '#F59E0B' },
    { label: 'Below 6', count: filteredStudents.filter(s => s.cgpa < 6).length, color: '#EF4444' },
  ];

  // Status pie data
  const statusData = [
    { name: 'Active', value: activeCount },
    { name: 'Graduated', value: graduatedCount },
    { name: 'Dropout', value: dropoutCount },
  ].filter(d => d.value > 0);

  // Semester distribution
  const semesterData = Array.from({ length: 8 }, (_, i) => ({
    name: `Sem ${i + 1}`,
    students: filteredStudents.filter(s => s.semester === i + 1).length,
  }));

  // Department performance rankings
  const deptData = useMemo(() => {
    const scopedDepts = role === 'COLLEGE_ADMIN'
      ? departments.filter(d => d.collegeId === currentUser.collegeId)
      : role === 'SUPER_ADMIN' && selectedCollegeId !== 'ALL'
        ? departments.filter(d => d.collegeId === selectedCollegeId)
        : departments;

    return scopedDepts.map(dept => {
      const deptStudents = filteredStudents.filter(s => s.departmentId === dept.id);
      const deptAvgCGPA = deptStudents.length > 0
        ? (deptStudents.reduce((sum, s) => sum + s.cgpa, 0) / deptStudents.length).toFixed(2)
        : '0.00';
      return {
        name: dept.code,
        fullName: dept.name,
        students: deptStudents.length,
        avgCGPA: parseFloat(deptAvgCGPA),
        active: deptStudents.filter(s => s.status === 'ACTIVE').length,
        graduated: deptStudents.filter(s => s.status === 'GRADUATED').length,
      };
    }).filter(d => d.students > 0).sort((a, b) => b.avgCGPA - a.avgCGPA);
  }, [filteredStudents, departments, role, currentUser, selectedCollegeId]);

  // Radar chart data for departments (top 6)

  // Top 10 performers
  const topPerformers = [...filteredStudents].sort((a, b) => b.cgpa - a.cgpa).slice(0, 10);

  const exportReport = () => {
    if (filteredStudents.length === 0) {
      toast.error('No data to export');
      return;
    }
    const lines = [
      `StuVault Analytics Report`,
      `Generated: ${format(new Date(), 'MMMM d, yyyy HH:mm')}`,
      `Generated By: ${currentUser.name} (${currentUser.role.replace(/_/g, ' ')})`,
      ``,
      `SUMMARY STATISTICS`,
      `Total Students: ${totalStudents}`,
      `Active: ${activeCount} (${totalStudents > 0 ? ((activeCount / totalStudents) * 100).toFixed(1) : 0}%)`,
      `Graduated: ${graduatedCount}`,
      `Dropout: ${dropoutCount}`,
      `Average CGPA: ${avgCGPA}`,
      `Excellence (9+): ${excellentCount} students`,
      ``,
      `DEPARTMENT RANKINGS (by Avg CGPA)`,
      ...deptData.map((d, i) => `${i + 1}. ${d.fullName} — Avg CGPA: ${d.avgCGPA} | Students: ${d.students}`),
      ``,
      `TOP 10 PERFORMERS`,
      ...topPerformers.map((s, i) => {
        const dept = departments.find(d => d.id === s.departmentId);
        return `${i + 1}. ${s.name} (${s.hallTicket}) — CGPA: ${s.cgpa.toFixed(2)} | ${dept?.name ?? 'N/A'} | Sem ${s.semester}`;
      }),
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `stuvault_report_${format(new Date(), 'yyyyMMdd_HHmmss')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report exported successfully');
  };

  return (
    <div className="space-y-8 font-sans animate-fade-in-up">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-3xl font-extrabold font-display text-slate-800 dark:text-slate-100 tracking-tight">
            Analytics &amp; Reports
          </h2>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Comprehensive academic performance insights and data summaries
          </p>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          {role === 'SUPER_ADMIN' && (
            <select
              value={selectedCollegeId}
              onChange={e => setSelectedCollegeId(e.target.value)}
              className="px-4 py-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm text-slate-700 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all font-medium"
            >
              <option value="ALL">All Colleges</option>
              {colleges.map(c => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
          )}
          <button
            onClick={exportReport}
            className="inline-flex items-center gap-2 px-4 py-2.5 border border-slate-200 dark:border-slate-700 rounded-xl shadow-sm text-sm font-semibold text-slate-700 dark:text-slate-200 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 transition-all cursor-pointer"
          >
            <Download className="h-4 w-4 text-slate-500" />
            Export Report
          </button>
        </div>
      </div>

      {/* KPI Summary Strip */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
        {[
          { label: 'Total Students', value: totalStudents, icon: Users, color: 'text-blue-600 bg-blue-50 border-blue-100' },
          { label: 'Active', value: activeCount, icon: GraduationCap, color: 'text-emerald-600 bg-emerald-50 border-emerald-100' },
          { label: 'Graduated', value: graduatedCount, icon: Award, color: 'text-indigo-600 bg-indigo-50 border-indigo-100' },
          { label: 'Dropout', value: dropoutCount, icon: TrendingUp, color: 'text-rose-600 bg-rose-50 border-rose-100' },
          { label: 'Avg CGPA', value: avgCGPA, icon: BarChart2, color: 'text-purple-600 bg-purple-50 border-purple-100' },
          { label: 'Excellence (9+)', value: excellentCount, icon: Award, color: 'text-amber-600 bg-amber-50 border-amber-100' },
        ].map((item) => (
          <div key={item.label} className={`border rounded-2xl p-4 flex flex-col gap-2 ${item.color.split(' ').slice(1).join(' ')}`}>
            <div className={`flex items-center gap-2 ${item.color.split(' ')[0]}`}>
              <item.icon className="h-4 w-4" />
              <span className="text-xs font-bold uppercase tracking-wider">{item.label}</span>
            </div>
            <p className={`text-2xl font-extrabold font-display ${item.color.split(' ')[0]}`}>{item.value}</p>
          </div>
        ))}
      </div>

      {/* CGPA Distribution + Status Pie */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* CGPA Distribution Bar */}
        <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
          <h3 className="text-lg font-bold font-display text-slate-800 dark:text-slate-100 mb-5">CGPA Distribution</h3>
          {filteredStudents.length > 0 ? (
            <div className="space-y-3">
              {cgpaRanges.map((range) => (
                <div key={range.label} className="flex items-center gap-3">
                  <span className="text-xs font-semibold text-slate-500 w-16 flex-shrink-0">{range.label}</span>
                  <div className="flex-1 bg-slate-100 rounded-full h-2.5 overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all duration-500"
                      style={{
                        width: totalStudents > 0 ? `${(range.count / totalStudents) * 100}%` : '0%',
                        backgroundColor: range.color
                      }}
                    />
                  </div>
                  <span className="text-xs font-bold text-slate-600 w-8 text-right">{range.count}</span>
                </div>
              ))}
            </div>
          ) : (
            <div className="h-32 flex items-center justify-center text-slate-400 text-sm">No data available</div>
          )}
        </div>

        {/* Status Donut */}
        <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
          <h3 className="text-lg font-bold font-display text-slate-800 dark:text-slate-100 mb-5">Enrollment Status</h3>
          <div className="h-52">
            {statusData.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={statusData}
                    cx="50%"
                    cy="50%"
                    innerRadius={55}
                    outerRadius={80}
                    paddingAngle={4}
                    dataKey="value"
                    label={({ name, percent }) => `${name} ${((percent || 0) * 100).toFixed(0)}%`}
                    labelLine={false}
                  >
                    {statusData.map((_, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip contentStyle={{ borderRadius: '12px', border: '1px solid #E2E8F0' }} />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-full flex items-center justify-center text-slate-400 text-sm">No data available</div>
            )}
          </div>
        </div>
      </div>

      {/* Semester Distribution */}
      <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
        <h3 className="text-lg font-bold font-display text-slate-800 dark:text-slate-100 mb-5">Students by Semester</h3>
        <div className="h-56">
          {filteredStudents.length > 0 ? (
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={semesterData} margin={{ top: 5, right: 10, left: -15, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                <XAxis dataKey="name" stroke="#94A3B8" fontSize={12} tickLine={false} />
                <YAxis stroke="#94A3B8" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip contentStyle={{ borderRadius: '12px', border: '1px solid #E2E8F0' }} />
                <Bar dataKey="students" name="Students" fill="#6366F1" radius={[6, 6, 0, 0]} barSize={32} />
              </BarChart>
            </ResponsiveContainer>
          ) : (
            <div className="h-full flex items-center justify-center text-slate-400 text-sm">No data available</div>
          )}
        </div>
      </div>

      {/* Department Rankings */}
      {deptData.length > 0 && (
        <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl overflow-hidden shadow-sm">
          <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
            <h3 className="text-lg font-bold font-display text-slate-800 dark:text-slate-100">Department Rankings</h3>
            <span className="text-xs font-semibold text-slate-400 bg-slate-100 px-3 py-1 rounded-full">Sorted by Avg CGPA</span>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-100">
              <thead className="bg-slate-50/75 dark:bg-slate-800/50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">Rank</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">Department</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">Students</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">Active</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">Graduated</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">Avg CGPA</th>
                </tr>
              </thead>
              <tbody className="bg-white dark:bg-slate-900 divide-y divide-slate-100 dark:divide-slate-800">
                {deptData.map((dept, idx) => (
                  <tr key={dept.name} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors">
                    <td className="px-6 py-3.5 text-sm font-bold text-slate-400">
                      {idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : `#${idx + 1}`}
                    </td>
                    <td className="px-6 py-3.5">
                      <div className="text-sm font-bold text-slate-800 dark:text-slate-200">{dept.fullName}</div>
                      <div className="text-xs text-slate-400 dark:text-slate-500 font-mono">{dept.name}</div>
                    </td>
                    <td className="px-6 py-3.5 text-sm font-semibold text-slate-600 dark:text-slate-400">{dept.students}</td>
                    <td className="px-6 py-3.5">
                      <span className="inline-flex items-center px-2 py-0.5 rounded-lg text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-100">
                        {dept.active}
                      </span>
                    </td>
                    <td className="px-6 py-3.5">
                      <span className="inline-flex items-center px-2 py-0.5 rounded-lg text-xs font-bold bg-indigo-50 text-indigo-700 border border-indigo-100">
                        {dept.graduated}
                      </span>
                    </td>
                    <td className="px-6 py-3.5">
                      <span className={`font-extrabold text-sm px-2.5 py-0.5 rounded-lg border ${
                        dept.avgCGPA >= 9 ? 'bg-emerald-50 text-emerald-700 border-emerald-100' :
                        dept.avgCGPA >= 7 ? 'bg-blue-50 text-blue-700 border-blue-100' :
                        'bg-amber-50 text-amber-700 border-amber-100'
                      }`}>
                        {dept.avgCGPA.toFixed(2)}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Top Performers */}
      {topPerformers.length > 0 && (
        <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl overflow-hidden shadow-sm">
          <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-800">
            <h3 className="text-lg font-bold font-display text-slate-800 dark:text-slate-100">Top 10 Performers</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-100">
              <thead className="bg-slate-50/75">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">#</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">Student</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">Hall Ticket</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">Department</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">Sem</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">CGPA</th>
                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-400 uppercase tracking-wider">Status</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-slate-100">
                {topPerformers.map((s, idx) => {
                  const dept = departments.find(d => d.id === s.departmentId);
                  return (
                    <tr key={s.id} className="hover:bg-slate-50/50 transition-colors">
                      <td className="px-6 py-3.5 text-sm font-bold text-slate-400">
                        {idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : `#${idx + 1}`}
                      </td>
                      <td className="px-6 py-3.5">
                        <div className="flex items-center gap-2.5">
                          <div className="h-8 w-8 rounded-xl bg-gradient-to-tr from-indigo-500 to-blue-500 flex items-center justify-center text-white font-bold text-xs flex-shrink-0 overflow-hidden">
                            {s.photoUrl ? (
                              <img src={s.photoUrl} alt={s.name} className="w-full h-full object-cover" />
                            ) : (
                              s.name.split(' ').map(n => n.charAt(0)).join('').slice(0, 2)
                            )}
                          </div>
                          <div>
                            <div className="text-sm font-bold text-slate-800">{s.name}</div>
                            <div className="text-xs text-slate-400">{s.email}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-3.5 text-sm font-mono font-medium text-slate-500">{s.hallTicket}</td>
                      <td className="px-6 py-3.5 text-sm text-slate-500 truncate max-w-[160px]">{dept?.name ?? '—'}</td>
                      <td className="px-6 py-3.5">
                        <span className="bg-slate-100 px-2 py-0.5 rounded-lg text-xs font-semibold text-slate-600">{s.semester}</span>
                      </td>
                      <td className="px-6 py-3.5">
                        <span className={`font-extrabold px-2.5 py-0.5 rounded-lg text-xs border ${
                          s.cgpa >= 9 ? 'bg-emerald-50 text-emerald-700 border-emerald-100' :
                          s.cgpa >= 7 ? 'bg-blue-50 text-blue-700 border-blue-100' :
                          'bg-amber-50 text-amber-700 border-amber-100'
                        }`}>
                          {s.cgpa.toFixed(2)}
                        </span>
                      </td>
                      <td className="px-6 py-3.5">
                        <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                          s.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' :
                          s.status === 'GRADUATED' ? 'bg-blue-50 text-blue-700 border border-blue-100' :
                          'bg-rose-50 text-rose-700 border border-rose-100'
                        }`}>
                          {s.status}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* College Comparison (SUPER_ADMIN only) */}
      {role === 'SUPER_ADMIN' && selectedCollegeId === 'ALL' && (
        <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
          <h3 className="text-lg font-bold font-display text-slate-800 dark:text-slate-100 mb-5">College-wise Comparison</h3>
          <div className="h-64">
            {colleges.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={colleges.map(c => ({
                    name: c.code,
                    students: students.filter(s => s.collegeId === c.id).length,
                    avgCGPA: (() => {
                      const cs = students.filter(s => s.collegeId === c.id);
                      return cs.length > 0 ? parseFloat((cs.reduce((a, s) => a + s.cgpa, 0) / cs.length).toFixed(2)) : 0;
                    })(),
                  }))}
                  margin={{ top: 5, right: 30, left: -15, bottom: 5 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                  <XAxis dataKey="name" stroke="#94A3B8" fontSize={12} tickLine={false} />
                  <YAxis yAxisId="left" stroke="#6366F1" fontSize={12} tickLine={false} axisLine={false} />
                  <YAxis yAxisId="right" orientation="right" stroke="#10B981" fontSize={12} tickLine={false} axisLine={false} domain={[0, 10]} />
                  <Tooltip contentStyle={{ borderRadius: '12px', border: '1px solid #E2E8F0' }} />
                  <Legend />
                  <Bar yAxisId="left" dataKey="students" name="Students" fill="#6366F1" radius={[6, 6, 0, 0]} barSize={24} />
                  <Bar yAxisId="right" dataKey="avgCGPA" name="Avg CGPA" fill="#10B981" radius={[6, 6, 0, 0]} barSize={24} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-full flex items-center justify-center text-slate-400 text-sm">No college data</div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
